<?php

$yahoo->codes[0] = 'Tornado';
$yahoo->codes[1] = 'Tropischer Sturm'; 
$yahoo->codes[2] = 'Hurrican'; 
$yahoo->codes[3] = 'schwere Gewitter';
$yahoo->codes[4] = 'Gewitter'; 
$yahoo->codes[5] = 'Schneeregen'; 
$yahoo->codes[6] = 'Graupelschauer'; 
$yahoo->codes[7] = 'Schnee-Graupel'; 
$yahoo->codes[8] = 'gefrierender Nebel'; 
$yahoo->codes[9] = 'Niesel'; 
$yahoo->codes[10] = 'gefrierender Nebel'; 
$yahoo->codes[11] = 'Schauer'; 
$yahoo->codes[12] = 'Schauer'; 
$yahoo->codes[13] = 'Schneegestöber'; 
$yahoo->codes[14] = 'leichter Schneefall'; 
$yahoo->codes[15] = 'Schneesturm'; 
$yahoo->codes[16] = 'Schneefall'; 
$yahoo->codes[17] = 'Hagel'; 
$yahoo->codes[18] = 'Graupel';
$yahoo->codes[19] = 'Dunst'; 
$yahoo->codes[20] = 'Nebel'; 
$yahoo->codes[21] = 'Trübe'; 
$yahoo->codes[22] = 'Rauchig'; 
$yahoo->codes[23] = 'Stürmisch'; 
$yahoo->codes[24] = 'Windig'; 
$yahoo->codes[25] = 'Kalt'; 
$yahoo->codes[26] = 'Wolkig'; 
$yahoo->codes[27] = 'Bewölkt'; // (Nacht)
$yahoo->codes[28] = 'Bewölkt'; // (Tag)
$yahoo->codes[29] = 'Teilweise bewölkt'; // (Nacht)
$yahoo->codes[30] = 'Teilweise bewölkt ';// (Tag)
$yahoo->codes[31] = 'Klar'; // (Nacht)
$yahoo->codes[32] = 'Sonnig';
$yahoo->codes[33] = 'Heiter'; // (Nacht)
$yahoo->codes[34] = 'Heiter'; // (Tag)
$yahoo->codes[35] = 'Regen und Hagel'; 
$yahoo->codes[36] = 'Heiß'; 
$yahoo->codes[37] = 'gelegentliche Gewitter'; 
$yahoo->codes[38] = 'einzelne Gewitter'; 
$yahoo->codes[39] = 'einzelne Gewitter'; 
$yahoo->codes[40] = 'teilweise Regen'; 
$yahoo->codes[41] = 'starker Schneefall'; 
$yahoo->codes[42] = 'einzelne Schneeschauer'; 
$yahoo->codes[43] = 'starker Schneefall'; 
$yahoo->codes[44] = 'teilweise wolkig'; 
$yahoo->codes[45] = 'Gewitter'; 
$yahoo->codes[46] = 'Schneeschauer'; 
$yahoo->codes[47] = 'gelegentliche Gewitter'; 
$yahoo->codes[3200] =  	"beschreibung konnte nicht abgerufen werden";